{"uid":"4b4757e66a1912dae1a509f688f20b0f","children":[{"name":"Test defects","children":[{"name":"`cy.request()` failed on:\n                \n                https://api.themoviedb.org/3/list\n                \n                The response we received from your web server was:\n                \n                  > 422: Unprocessable Entity\n                \n                This was considered a failure because the status code was not `2xx` or `3xx`.\n                \n                If you do not want status codes to cause failures pass the option: `failOnStatusCode: false`\n                \n                -----------------------------------------------------------\n                \n                The request we sent was:\n                \n                Method: POST\n                URL: https://api.themoviedb.org/3/list\n                Headers: {\n                  \"Connection\": \"keep-alive\",\n                  \"Authorization\": \"Bearer eyJhbGciOiJIUzI1NiJ9.eyJhdWQiOiI5ODE4ZDY4Nzc4MDcwYTY5ZGZmZmFmNDk3ZDIwNmM2YiIsInN1YiI6IjVmZWNiNDNkMGYzNjU1MDA0MGFhNDQ2YSIsInNjb3BlcyI6WyJhcGlfcmVhZCJdLCJ2ZXJzaW9uIjoxfQ.StSlwHbuW2FlD3BsS2Gm2A6eFANRUphotZJs39R2ipE\",\n                  \"user-agent\": \"Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Cypress/12.17.1 Chrome/106.0.5249.51 Electron/21.0.0 Safari/537.36\",\n                  \"accept\": \"*/*\",\n                  \"accept-encoding\": \"gzip, deflate\",\n                  \"content-type\": \"application/json\",\n                  \"content-length\": 130\n                }\n                Body: {\"name\":\"Teste da automação\",\"description\":\"Lista criada para que os testes automatizados sejam executados.\",\"language\":\"pt-br\"}\n                \n                -----------------------------------------------------------\n                \n                The response we got was:\n                \n                Status: 422 - Unprocessable Entity\n                Headers: {\n                  \"content-type\": \"application/json\",\n                  \"content-length\": \"65\",\n                  \"connection\": \"keep-alive\",\n                  \"date\": \"Fri, 21 Jul 2023 18:43:33 GMT\",\n                  \"server\": \"openresty\",\n                  \"cache-control\": \"public, max-age=0\",\n                  \"x-cache\": \"Error from cloudfront\",\n                  \"via\": \"1.1 10bf5e2f3ff7eaefa287c49657b8a838.cloudfront.net (CloudFront)\",\n                  \"x-amz-cf-pop\": \"DFW57-P2\",\n                  \"alt-svc\": \"h3=\\\":443\\\"; ma=86400\",\n                  \"x-amz-cf-id\": \"CIsIGNOP7-z_lYDL07ptrbAy6x1u2O8-nA22jEAxveVNXgaCUMZs3Q==\",\n                  \"vary\": \"Origin\"\n                }\n                Body: {\n                  \"errors\": [\n                    \"Invalid description\"\n                  ],\n                  \"success\": false,\n                  \"list_id\": null\n                }\n                \n                \n                https://on.cypress.io/request\n                \n                Because this error occurred during a `before all` hook we are skipping the remaining tests in the current suite: `Validar o enpoint DELETE /l...`","children":[{"name":"\"before all\" hook for \"Validar exclusão de uma lista com sucesso\"","uid":"43c54bd39681b655","parentUid":"e424c514624d9897d8430b64c206c798","status":"broken","time":{"start":1689965013956,"stop":1689965013956,"duration":0},"flaky":false,"newFailed":false,"newPassed":false,"newBroken":false,"retriesCount":0,"retriesStatusChange":false,"parameters":[]}],"uid":"e424c514624d9897d8430b64c206c798"}],"uid":"bdbf199525818fae7a8651db9eafe741"}],"name":"categories"}